name: 'Terraform CI'

on:
  push:
    branches:
    - dev
    - prod
  pull_request:

env:
  TF_TOKEN_FORMAT: 'access_token'
  TF_WORKLOAD_ID_PROVIDER: 'projects/874395041100/locations/global/workloadIdentityPools/iac-pool/providers/github'
  TF_SERVICE_ACCOUNT: 'gh-actions@interstellar-14.iam.gserviceaccount.com'
  TF_ACCESS_TOKEN_LIFETIME: '300s'

jobs:
  Get_OIDC_ID_token:
  # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'

    # Configure Workload Identity Federation via a credentials file.
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0.3.1'
      with:
          create_credentials_file: 'true'
          token_format: '${{ env.TF_TOKEN_FORMAT }}'
          workload_identity_provider: '${{ env.TF_WORKLOAD_ID_PROVIDER }}'
          service_account: '${{ env.TF_SERVICE_ACCOUNT }}'
          access_token_lifetime: '${{ env.TF_ACCESS_TOKEN_LIFETIME }}' # optional, default: '3600s' (1 hour)

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
####
    - name: Terraform Destroy
      run: |
        terraform init
        terraform destroy -target=module.sf-poc --auto-approve
####
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      
    - name: Convert Plan to JSON
      run: terraform show -json tfplan > tfplan.json

    - name: Install OPA
      run: |
        curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
        chmod +x opa
        sudo mv opa /usr/local/bin/

    - name: Run OPA Evaluation
      run: opa eval -i tfplan.json -d policies/opa_policy.rego "data.terraform.analysis.authz"
      
    - name: Terraform Apply
      if: github.ref == 'refs/heads/prod' && github.event_name == 'push'
      run: terraform apply -auto-approve

####
    - name: Terraform Destroy
      run: |
        terraform init
        terraform destroy -target=module.sf-poc --auto-approve
####
