name: 'Terraform CI'

on:
  push:
    branches:
    - dev
  pull_request:

jobs:
  Get_OIDC_ID_token:
  # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-18.04
    steps:
    - uses: 'actions/checkout@v3'

    # Configure Workload Identity Federation via a credentials file.
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0.3.1'
      with:
          create_credentials_file: 'true'
          token_format: 'access_token'
          workload_identity_provider: 'projects/874395041100/locations/global/workloadIdentityPools/iac-pool/providers/github'
          service_account: 'gh-actions@interstellar-14.iam.gserviceaccount.com'
          access_token_lifetime: '300s' # optional, default: '3600s' (1 hour)


    - run: |-
        terraform init -var "access_token=${{ steps.auth.outputs.access_token }}" -backend-config="prefix=tf-state" -backend-config="${{ github.workspace }}/backend.tf"
